### ISSUE TITLE
Doc problems

### ISSUE THREAD

**Issue by jrochkind** [ostinelli/net-http2#1]
The README examples for `async_get` use `get` not `async_get`. A typo?  Confusing. 

     client.get('/path1') { |response_1| p response_2 }

I think you mean:

     client.async_get('/path1') { |response_1| p response_2 }

yes?

**Comment by ostinelli** [comment]
Yes it's a typo, thank you for noticing :) The async APIs will be revised, because I want to allow taking advantage of the instant replies that HTTP/2 offers (right now, everything gets buffered).

Will edit it tonight.

**Comment by ostinelli** [comment]
I've currently removed async calls, as per my documentation I am reviewing them to allow for HTTP/2 goodness. This hence is not in the documentation anymore, closing.
