### ISSUE TITLE
Client.new with proxy

### ISSUE THREAD

**Issue by mvalitov** [ostinelli/net-http2#12]
Hi, as I understand, there is support for the use of a proxy.
Could you show an example of such a code?
I tried to pass it so:
`client = NetHttp2::Client.new("http://nghttp2.org", {proxy_addr: "127.0.0.1", proxy_port: "8080"})`
but it did not help. Thanks

**Comment by Nattfodd** [comment]
It's not supported yet, there is a [PR](https://github.com/ostinelli/net-http2/pull/11) for it. If it will be accepted, it will look like you wrote.

**Comment by mvalitov** [comment]
ok, thanks
