### ISSUE TITLE
add ability to configure http-2 client

### ISSUE THREAD

**Issue by Fivell** [ostinelli/net-http2#17]
hello, thanks for this gem,
we experience ```HTTP2::Error::StreamLimitExceeded``` exception when using this gem with rpush. Looks like we need to configure ```settings_max_concurrent_streams``` option
I noticed we can't configure http2 client using params for constructor
https://github.com/igrigorik/http-2/blob/ea9cbd06d0e05641a5d6cfe2f31d584d3f839721/lib/http/2/connection.rb#L76

Any thoughts ? Thanks

**Comment by ostinelli** [comment]
https://github.com/ostinelli/net-http2/pull/22 has been just merged in. @benubois is showing how this can be used in Apnotic https://github.com/ostinelli/apnotic/commit/d5481eca2a3d45e3388b3e045f532eb7b08772bf
