### ISSUE TITLE
[Question] Timeouts for async calls

### ISSUE THREAD

**Issue by nattfodd** [ostinelli/net-http2#19]
I have a code that sends multiple async requests to the server. After all async calls are made, I call `@client.join` to wait until streams are closed. But sometimes they aren't for a huge amount of time (2-3 hours).

I read, that I need to implement my own timeout logic for such case. Okay. If I just wrap `.join` with a timeout, it's okay:
```ruby
begin
  Timeout.timeout(60) { @client.join }
rescue Timeout::Error
  # Some code executed after failure
end
```

But, in a current implementation, we just stop waiting for streams and go next. But what I need is to detect which async calls were successful, and which ones were not, and then retry failed deliveries later.

Is there any recommended way to deal with it, or should I go back to a slower sync requests? And is there any way to close some streams that timeouted?

**Comment by ostinelli** [comment]
I would avoid using the `Timeout` module as much as possible ([reference](http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/)).

To solve this, an addition to the library is probably needed. I'd suspect the best place to implement a timeout would be [here](https://github.com/ostinelli/net-http2/blob/0.15.0/lib/net-http2/stream.rb#L100) by specifying a timeout in the [ConditionVariable#wait](http://ruby-doc.org/core-2.3.0_preview1/ConditionVariable.html#method-i-wait) call. Then it would just be a matter of propagating the option from the async call to there.

**Comment by jhottenstein** [comment]
We are currently running into a problem with this as well.

Would an elapsed time check inside `client#join` be ok with you?  Something like:
```
    def join
      starting_time = Process.clock_gettime(Process::CLOCK_MONOTONIC)
      while !@streams.empty? && Process.clock_gettime(Process::CLOCK_MONOTONIC) - starting_time < @join_timeout do
        sleep 0.05
      end
    end
```
