### ISSUE TITLE
reconnect?

### ISSUE THREAD

**Issue by singpolyma-shopify** [ostinelli/net-http2#36]
If the socket connection terminates, it looks like the socket loop will terminate but not be re-opened by `ensure_open` ... what is the right way to handle reconnects?

**Comment by singpolyma-shopify** [comment]
After more testing... reconnects seem to "just work" so long as an error callback is set on the client.

**Comment by akostadinov** [comment]
But seems like a back-off algorithm would be nice to have with this. Otherwise it would be hard to make multiple threads know that there was a disconnection and to wait before trying to do something.
