### ISSUE TITLE
add timeout setting for "connect"

### ISSUE THREAD

**Issue by stillwaiting** [ostinelli/net-http2#5]
There could be a situation when a server doesn't respond on connection (like [here](https://forums.developer.apple.com/message/137557)), so it fails. But the default timeout is huge: on my side it is ~90 seconds. Would it be possible to introduce it as an option (something like [here](http://stackoverflow.com/a/32752835/1432640)).

Thanks.

**Comment by ostinelli** [comment]
If we implement such an option, we need to do so also for the non-SSL connections. Your example points to a SSL one, but this requires using `Socket` instead of `TCPSocket` too.

**Comment by ostinelli** [comment]
I've added a new client option `connect_timeout ` that should do what you ask.

Can you please try out master and see if this works for you?

**Comment by stillwaiting** [comment]
Looks like it does the trick, but, unfortunately, apnotic is broken now: [here](https://github.com/ostinelli/apnotic/blob/1e8fe569ee6f2a76135de152f58622f16dd5e14a/lib/apnotic/connection.rb#L27) `:connection_timeout` key is passed while net-http2 [expects](https://github.com/ostinelli/net-http2/blob/b583a228db0f76ada9a2fd9a7d73a3c97198679e/lib/net-http2/client.rb#L15) `:connect_timeout`

**Comment by ostinelli** [comment]
Indeed. Will merge in. Closing here :)
