### ISSUE TITLE
sleep time in stream.rb and client.rb

### ISSUE THREAD

**Issue by adamvduke** [ostinelli/net-http2#6]
Hi, first I wanted to say thanks for contributing the gem! We're using apnotic to try out the HTTP2 APNS endpoints and see the time to complete a request has a consistent floor very near 100ms.

![screen shot 2016-05-20 at 3 19 23 pm](https://cloud.githubusercontent.com/assets/94930/15439906/7a744de0-1ea0-11e6-8750-e89e6128c808.png)

I was wondering how the times to sleep were decided on [here](https://github.com/ostinelli/net-http2/blob/7837bdca612fe886cc65b671300c74c9b311fad7/lib/net-http2/stream.rb#L91) and [here](https://github.com/ostinelli/net-http2/blob/7837bdca612fe886cc65b671300c74c9b311fad7/lib/net-http2/client.rb#L119). Is there a specific reason 100ms is used and/or can it be made smaller or configurable?

**Comment by ostinelli** [comment]
Hi @adamvduke, we can totally make it smaller & configurable. Give me a couple of days and I'll issue a change. Would you mind giving me your feedback then?

Also, a side question: how many pushes are you doing / day?

**Comment by adamvduke** [comment]
The current throughput for this particular service is ~10k/day, but the expected throughput is 10's of millions.

**Comment by ostinelli** [comment]
This commit gets rid of any delay, and will instantly unlock the blocking call ASA the response is received.

Can you try master with Apnotic and see if this works for you?

**Comment by acceber95** [comment]
Hi @ostinelli,

The temp branch of apnotic would be helpful because the version of net-http2 has changed from `~> 0.9.2` in source to `~> 0.10.0` which causes some issues with bundler when trying to resolve correct versions based on apnotic's current gemspec.

cc @adamvduke

**Comment by ostinelli** [comment]
I realized that my proposal is undoable, since I cannot specify a gem dependency on a branch.

Can't you just specify in your `Gemfile`:

```ruby
gem 'apnotic', '~> 0.9'
gem 'net-http2', git: 'https://github.com/ostinelli/net-http2.git', :ref => 'a86074ce406db68190ec50a344d521d71ec91ee6'
```

**Comment by ostinelli** [comment]
I _have_ released v0.11.1 of NetHttp2, as you can see on the RubyGems [gem page](https://rubygems.org/gems/net-http2), however even if I can [download](https://rubygems.org/downloads/net-http2-0.11.1.gem) it, I cannot install it with bundler:

```
$ gem install net-http2 -v 0.11.1
ERROR:  Could not find a valid gem 'net-http2' (= 0.11.1) in any repository
ERROR:  Possible alternatives: net-http2
```

I guess RubyGems is experiencing some issues.

**Comment by ostinelli** [comment]
Will release apnotic `0.9.2` tonight.

**Comment by ostinelli** [comment]
`0.9.2` has been released.

I haven't heard back from you @adamvduke, let me know if this solves your issue.

**Comment by adamvduke** [comment]
I will try to test it out this week.

**Comment by ostinelli** [comment]
Hello @adamvduke, any news on this?

**Comment by adamvduke** [comment]
We've seen the timing drop down to around 75ms on average and it is not a hard floor anymore. We haven't seen a noticeable change in response codes or exception rates from Apple, which seems to indicate things are working well.

![screen shot 2016-05-31 at 11 27 56 am](https://cloud.githubusercontent.com/assets/94930/15680321/469d6ec6-2723-11e6-9cfa-4797a4e9762d.png)

**Comment by ostinelli** [comment]
Thank you for the feedback, @adamvduke. If you end up using Apnotic for the millions pushes that you were referring to, please let me know :)
